name: Weekly Crawl Data

on:
  schedule:
    - cron: '0 3 * * 0'  # 03:00 UTC every Sunday
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          # Provide cookie string via repo secret if you need access to premium content
          CULTFIT_COOKIE_STRING: ${{ secrets.CULTFIT_COOKIE_STRING }}
        run: |
          python cultfit_crawler.py

      - name: Detect repository changes
        id: changed
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated data & README
        if: steps.changed.outputs.has_changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            data/
          message: 'chore(data): weekly crawl'
          default_author: github_actions 